### ISSUE TITLE
add Session attributes to Spatial Annotations to construct description in app

### ISSUE THREAD

**Issue by phivk** [polifonia-project/sonar2021_data_transformation#11]
as reported by @JaseMK via emai:

> I’m thinking about our conversations last Friday and the “Musical Locations” title and how we can make it better. One small improvement would be to replace with something like just “Location” but, as discussed, a better solution would be a short label specific to that Annotation, so that we don’t have repeated instances of “Location” appearing in the stream. For example… “Mixing location: London” would be better.

In the KG, Recordings are related to Places via one or more Sessions. Sessions can be of different types, e.g.:

- mp:ProductionSession
- mp:RecordingSession
- mp:MixdownSession
- mp:EditingSession

We should add this SessionType attribute to annotations, so a description / motivation can be constructed and formatted more flexibly in the Sonar App.

@JaseMK Apologies, I had previously proposed to add these SessionTypes, but forgot to include them. 
Are you ok with the approach described above?

**Comment by JaseMK** [comment]
Thanks @phivk, yes that would be ideal.

**Comment by phivk** [comment]
I'll put all this place information into the annotation metadata object, using original field names from the Polifonia KG:
```
"metadata": {
  "placeLabel": "Metropolis",
  "placeFullAddress": "The Power House, 70 Chiswick High Road, London, W4 1SY",
  "placeLong": "-0.249623",
  "placeLat": "51.493699",
  "sessionTypeLabel": "recorded at"
},
```
