### ISSUE TITLE
Create harmonics annotations

### ISSUE THREAD

**Issue by ccolonna** [polifonia-project/sonar2021_data_transformation#13]
The ontology to have an idea of data model is [here](https://github.com/polifonia-project/sonar2021_demo/issues/21)

**Comment by phivk** [comment]
@JaseMK and I discussed what the app data model could look like for HarmonicAnnotations, to represent harmonic similarities between two songs via their longest (similar) chord progression:

```
{
  "id": "asd;hasdoifasfiajsd",
  "type": "harmonic",
  "songID": "https://w3id.org/polifonia/resource/Recording/00197",
  "timestamp": 2.8,
  "metadata": {
    "longestChordProgression": "A:m, G:m, A:m",
    "timestampIn": 2.8,
    "timestampOut": 6.3
  },
  "relationships": [
    {
      "annotationID": "askdhuflasiudfha678ocus",
      "type": "harmonic",
      "score": 0.82
    }
  ]
}
```

**Comment by delfimpandiani** [comment]
Hi @phivk, you can find the test turtle file [here](https://github.com/polifonia-project/KG_data_transformation/blob/harmonic-similarity-transformation/harmonic_sim_etl/kg/versions/polifonia-kg-harmonic-test.ttl). It has two examples of harmonic similarity. I copy the test turtle below also for easy access. Hope this is helpful!

The harmonic similarity ontology module will be arriving soon, @FiorelaCiroku will be uploading it and linking it to a comment in this thread asap :-)



```
@prefix core:  <https://w3id.org/polifonia/ON/core/> .
@prefix pr:    <https://w3id.org/polifonia/resource/> .
@prefix fx:    <http://sparql.xyz/facade-x/ns/> .
@prefix mp:    <https://w3id.org/polifonia/ON/musical-performance/> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix mc:    <https://w3id.org/polifonia/ON/musical-composition/> .
@prefix xyz:   <http://sparql.xyz/facade-x/data/> .
@prefix mf:    <https://w3id.org/polifonia/ON/musical-feature/> .
@prefix cm:    <https://w3id.org/polifonia/ON/comparative-measure/> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .

<https://w3id.org/polifonia/resource/ChordProgression/00339_C%23_F%235_C%23>
        a                        mf:ChordProgression ;
        cm:isInvolvedinHarmonicSimilarity
                <https://w3id.org/polifonia/resource/HarmonicSimilarity/harm_sim_00424_00339> ;
        mf:hasEndInRecording     "0:01:58.925813" ;
        mf:hasStartInRecording   "0:00:01.206300" ;
        mf:isChordProgressionOf  <https://w3id.org/polifonia/resource/Recording/00339> .

<https://w3id.org/polifonia/resource/Recording/08888>
        a                           mp:Recording ;
        cm:isHarmonicallySimilarTo  <https://w3id.org/polifonia/resource/Recording/00111> ;
        cm:isInvolvedinHarmonicSimilarity
                <https://w3id.org/polifonia/resource/HarmonicSimilarity/harm_sim_08888_00111> ;
        mf:hasChordProgression      <https://w3id.org/polifonia/resource/ChordProgression/08888_AmajB_Fmaj_D> .

<https://w3id.org/polifonia/resource/ChordProgression/00424_GmajB_Cmaj_GmajD>
        a                        mf:ChordProgression ;
        cm:isInvolvedinHarmonicSimilarity
                <https://w3id.org/polifonia/resource/HarmonicSimilarity/harm_sim_00424_00339> ;
        mf:hasEndInRecording     "0:01:03.700000" ;
        mf:hasStartInRecording   "0:01:01.320000" ;
        mf:isChordProgressionOf  <https://w3id.org/polifonia/resource/Recording/00424> .

<https://w3id.org/polifonia/resource/Recording/00339>
        a                           mp:Recording ;
        cm:isHarmonicallySimilarTo  <https://w3id.org/polifonia/resource/Recording/00424> ;
        cm:isInvolvedinHarmonicSimilarity
                <https://w3id.org/polifonia/resource/HarmonicSimilarity/harm_sim_00424_00339> ;
        mf:hasChordProgression      <https://w3id.org/polifonia/resource/ChordProgression/00339_Fmaj%23_G%235_C%23> , <https://w3id.org/polifonia/resource/ChordProgression/00339_C%23_F%235_C%23> .

<https://w3id.org/polifonia/resource/Recording/00424>
        a                           mp:Recording ;
        cm:isHarmonicallySimilarTo  <https://w3id.org/polifonia/resource/Recording/00339> ;
        cm:isInvolvedinHarmonicSimilarity
                <https://w3id.org/polifonia/resource/HarmonicSimilarity/harm_sim_00424_00339> ;
        mf:hasChordProgression      <https://w3id.org/polifonia/resource/ChordProgression/00424_Fmaj_Cmaj_Fmaj> , <https://w3id.org/polifonia/resource/ChordProgression/00424_GmajB_Cmaj_GmajD> .

<https://w3id.org/polifonia/resource/ChordProgression/00111_C%23_F%235_C%23>
        a                        mf:ChordProgression ;
        cm:isInvolvedinHarmonicSimilarity
                <https://w3id.org/polifonia/resource/HarmonicSimilarity/harm_sim_08888_00111> ;
        mf:hasEndInRecording     "0:01:48.00000" ;
        mf:hasStartInRecording   "0:01:01.206300" ;
        mf:isChordProgressionOf  <https://w3id.org/polifonia/resource/Recording/00111> .

<https://w3id.org/polifonia/resource/ChordProgression/00424_Fmaj_Cmaj_Fmaj>
        a                        mf:ChordProgression ;
        cm:isInvolvedinHarmonicSimilarity
                <https://w3id.org/polifonia/resource/HarmonicSimilarity/harm_sim_00424_00339> ;
        mf:hasEndInRecording     "0:03:53.900000" ;
        mf:hasStartInRecording   "0:03:51.70000" ;
        mf:isChordProgressionOf  <https://w3id.org/polifonia/resource/Recording/00424> .

<https://w3id.org/polifonia/resource/ChordProgression/00339_Fmaj%23_G%235_C%23>
        a                        mf:ChordProgression ;
        cm:isInvolvedinHarmonicSimilarity
                <https://w3id.org/polifonia/resource/HarmonicSimilarity/harm_sim_00424_00339> ;
        mf:hasEndInRecording     "0:03:09.124000" ;
        mf:hasStartInRecording   "0:02:45.320000" ;
        mf:isChordProgressionOf  <https://w3id.org/polifonia/resource/Recording/00339> .

<https://w3id.org/polifonia/resource/HarmonicSimilarity/harm_sim_00424_00339>
        a                            cm:HarmonicSimilarity ;
        cm:hasSimScore               "0.9"^^<http://www.w3.org/2001/XMLSchema#float> ;
        cm:involvesChordProgression  <https://w3id.org/polifonia/resource/ChordProgression/00424_Fmaj_Cmaj_Fmaj> , <https://w3id.org/polifonia/resource/ChordProgression/00424_GmajB_Cmaj_GmajD> ;
        cm:involvesRecording         <https://w3id.org/polifonia/resource/Recording/00339> , <https://w3id.org/polifonia/resource/Recording/00424> .

<https://w3id.org/polifonia/resource/HarmonicSimilarity/harm_sim_08888_00111>
        a                            cm:HarmonicSimilarity ;
        cm:hasSimScore               "0.5"^^<http://www.w3.org/2001/XMLSchema#float> ;
        cm:involvesChordProgression  <https://w3id.org/polifonia/resource/ChordProgression/08888_AmajB_Fmaj_D> ;
        cm:involvesRecording         <https://w3id.org/polifonia/resource/Recording/00111> , <https://w3id.org/polifonia/resource/Recording/08888> .

<https://w3id.org/polifonia/resource/Recording/00111>
        a                           mp:Recording ;
        cm:isHarmonicallySimilarTo  <https://w3id.org/polifonia/resource/Recording/08888> ;
        cm:isInvolvedinHarmonicSimilarity
                <https://w3id.org/polifonia/resource/HarmonicSimilarity/harm_sim_08888_00111> ;
        mf:hasChordProgression      <https://w3id.org/polifonia/resource/ChordProgression/00111_C%23_F%235_C%23> .

<https://w3id.org/polifonia/resource/ChordProgression/08888_AmajB_Fmaj_D>
        a                        mf:ChordProgression ;
        cm:isInvolvedinHarmonicSimilarity
                <https://w3id.org/polifonia/resource/HarmonicSimilarity/harm_sim_08888_00111> ;
        mf:hasEndInRecording     "0:10:03.700000" ;
        mf:hasStartInRecording   "0:09:01.320000" ;
        mf:isChordProgressionOf  <https://w3id.org/polifonia/resource/Recording/08888> .
```

**Comment by phivk** [comment]
latest version of (full) harmonic similarities graph:
https://github.com/polifonia-project/KG_data_transformation/blob/feature/harmonic-similarity-transformation/harmonic_sim_etl/kg/versions/polifonia-kg-harmonic-0.0.1.ttl

**Comment by phivk** [comment]
I finalised the query & transformation based on the above [test ttl file](https://github.com/polifonia-project/sonar2021_data_transformation/issues/13#issuecomment-943385727) and have pushed these updates to the [develop branch](https://github.com/polifonia-project/sonar2021_data_transformation/commits/develop).

I have [signalled](https://github.com/polifonia-project/KG_data_transformation/issues/6) an issue when more than 2 ChordProgressions are linked to a HarmonicSimilarity. @ccolonna is looking into a solution on the KG side, which I will integrate when it's ready.

With the test file working, I tried the using [polifonia-kg-harmonic-0.0.1.ttl](https://github.com/polifonia-project/KG_data_transformation/blob/feature/harmonic-similarity-transformation/harmonic_sim_etl/kg/versions/polifonia-kg-harmonic-0.0.1.ttl) as input, but this gives me a timeout when I [try the query in a web client](https://comunica-web-client.vercel.app/#datasources=https%3A%2F%2Fraw.githubusercontent.com%2Fpolifonia-project%2FKG_data_transformation%2Ffeature%2Fharmonic-similarity-transformation%2Fharmonic_sim_etl%2Fkg%2Fversions%2Fpolifonia-kg-harmonic-0.0.1.ttl&query=PREFIX%20core%3A%20%20%3Chttps%3A%2F%2Fw3id.org%2Fpolifonia%2FON%2Fcore%2F%3E%0APREFIX%20pr%3A%20%20%20%20%3Chttps%3A%2F%2Fw3id.org%2Fpolifonia%2Fresource%2F%3E%0APREFIX%20fx%3A%20%20%20%20%3Chttp%3A%2F%2Fsparql.xyz%2Ffacade-x%2Fns%2F%3E%0APREFIX%20mp%3A%20%20%20%20%3Chttps%3A%2F%2Fw3id.org%2Fpolifonia%2FON%2Fmusical-performance%2F%3E%0APREFIX%20rdf%3A%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX%20mc%3A%20%20%20%20%3Chttps%3A%2F%2Fw3id.org%2Fpolifonia%2FON%2Fmusical-composition%2F%3E%0APREFIX%20xyz%3A%20%20%20%3Chttp%3A%2F%2Fsparql.xyz%2Ffacade-x%2Fdata%2F%3E%0APREFIX%20mf%3A%20%20%20%20%3Chttps%3A%2F%2Fw3id.org%2Fpolifonia%2FON%2Fmusical-feature%2F%3E%0APREFIX%20cm%3A%20%20%20%20%3Chttps%3A%2F%2Fw3id.org%2Fpolifonia%2FON%2Fcomparative-measure%2F%3E%0APREFIX%20rdfs%3A%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0A%0ASELECT%20DISTINCT%20%3FharmSim%20%3FsimScore%20%3FchordProgression%20%3FstartInRecording%20%3FendInRecording%20%3FsourceRecordingID%20%3FtargetRecordingID%0AWHERE%20%7B%20%20%0A%20%20%3FharmSim%0A%20%20%20%20rdf%3Atype%20cm%3AHarmonicSimilarity%20%3B%0A%20%20%20%20cm%3AhasSimScore%20%3FsimScore%20%3B%0A%20%20%20%20cm%3AinvolvesChordProgression%20%3FchordProgression%20%3B%0A%20%20%20%20cm%3AinvolvesRecording%20%3FsourceRecordingID%2C%20%3FtargetRecordingID%20%3B%0A%20%20.%0A%20%20%0A%20%20FILTER(%0A%20%20%20%20%3FsourceRecordingID%20!%3D%20%3FtargetRecordingID%0A%20%20)%20.%0A%20%20%0A%20%20%3FchordProgression%0A%20%20%20%20mf%3AisChordProgressionOf%20%20%3FsourceRecordingID%20%3B%0A%20%20%20%20mf%3AhasEndInRecording%20%20%20%20%20%3FendInRecording%20%3B%0A%20%20%20%20mf%3AhasStartInRecording%20%20%20%3FstartInRecording%20%3B%0A%20%20.%0A%7D). 

On the command line I get a out of memory error: `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

To be sure, I tried a [simple query to get 100 triples](https://comunica-web-client.vercel.app/#datasources=https%3A%2F%2Fraw.githubusercontent.com%2Fpolifonia-project%2FKG_data_transformation%2Ffeature%2Fharmonic-similarity-transformation%2Fharmonic_sim_etl%2Fkg%2Fversions%2Fpolifonia-kg-harmonic-0.0.1.ttl&query=CONSTRUCT%20WHERE%20%7B%0A%20%20%3Fs%20%3Fp%20%3Fo.%0A%7D%0ALIMIT%20100), which works although it takes 20 seconds.

To me this seems an issue of the huge ttl file size (81.4 MB).
@ccolonna @FiorelaCiroku @delfimpandiani Do you have any suggestions to make the querying more manageable?
Could a curated selection (that @andreamust and @vpresutti have started working on) help out?

**Comment by ccolonna** [comment]
Hi @phivk. Having a SPARQL Endpoint will probably remove any of this timeout issues querying file. Let's discuss this in the today's meeting. The KG is changing again. And we will reach the final version by tonight or tomorrow morning at most.

**Comment by ccolonna** [comment]
Hey @phivk ! meanwhile a smaller version of the KG for dev purpose [here](https://github.com/polifonia-project/KG_data_transformation/blob/master/harmonic_sim_etl/kg/versions/polifonia-kg-harmonic-0.0.2dev.ttl)

**Comment by phivk** [comment]
sparql endpoint: 
https://arco.istc.cnr.it/polifonia/sparql
repo:
https://github.com/polifonia-project/kg_sparql_endpoint
