### ISSUE TITLE
create short KG sample for development

### ISSUE THREAD

**Issue by phivk** [polifonia-project/sonar2021_data_transformation#14]
the [current KG file](https://raw.githubusercontent.com/polifonia-project/sonar2021_demo/datasets/polifonia_places_etl/kg/versions/polifonia-kg-places-0.0.2b.ttl) contains many entries, resulting in very long query times. 
for development & testing purposes it would be neat to have a short sample file, in .tll format, to test query and transformation functionality more quickly.

**Comment by ccolonna** [comment]
[Here](https://raw.githubusercontent.com/polifonia-project/KG_data_transformation/feature/short-dev-file/polifonia_places_etl/kg/versions/polifonia-kg-places-0.0.2b-limit.ttl) a KG for dev purpose.

**Comment by phivk** [comment]
works great @ccolonna!
